import "./globals.css";
import InviteFriend from "@/components/InviteFriend/InviteFriend";


export const metadata = {
  title: "LifeStyleAI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white" >
        <InviteFriend />
        {children}
      </body>
    </html>
  );
}
