import { Inter } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';

// const Azonix = localFont({ src: '/fonts/Azonix.otf' });

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-black text-white" >
        {children}
      </body>
    </html>
  );
}
